# Generated by Django 2.2.16 on 2021-11-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'managed': False},
        ),
    ]
