# Generated by Django 2.2.16 on 2021-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211128_1720'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='follow_unique'),
        ),
    ]
