# Generated by Django 2.2.16 on 2021-11-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211128_1800'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='super_const',
        ),
    ]
